### ISSUE TITLE
API GET request does not return all markets

### ISSUE THREAD

**Issue by robpal1990** [RadarRelay/sdk#58]
I am writing a bot in Python and wanted to access Radar's orderbooks from your endpoint

`https://api.radarrelay.com/v2/markets`

However, the command 

`curl https://api.radarrelay.com/v2/markets`

returns only 20 markets and there are many more (for example FUN-wETH and EMONT-wETH are missing in the response). Same happens in my code, when I post a GET request using `requests` module.

Is it just me or there's something wrong here?

**Comment by smithki** [comment]
The markets endpoint is paginated and should return 20 results per page by default. You can customize or narrow the request using the query parameters `page` and `perPage` (check out the docs [here](https://developers.radarrelay.com/feed-api/v2/#list-markets)). One potential gotcha is that `perPage` is capped at `100`, so you may need to submit consecutive requests and increment the `page` indicated.

**Comment by smithki** [comment]
Here's a short example as well:

https://api.radarrelay.com/v2/markets
  => Returns first 20 markets.

https://api.radarrelay.com/v2/markets?perPage=50
  => Returns first 50 markets. (`page` implicitly equals `1` here).

https://api.radarrelay.com/v2/markets?page=2&perPage=50
  => Returns markets 51-100.

**Comment by smithki** [comment]
Any time. We can certainly be more clear about this in our documentation and I’ll pass that along to the team. Thanks for opening an issue.
